apiVersion: v1
data:
  JWT_SECRET: dmFyc2hhMTIz
  MONGO_URI: bW9uZ29kYitzcnY6Ly8wMWZlMjNiY3MwNDdfZGJfdXNlcjpoaDRTNW5KejRQVXlMbFVuQGNsdXN0ZXIwLnFiYWR6eXEubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  PORT: NTAwMA==
kind: Secret
metadata:
  name: backend-env
